# Generated by Django 2.0.3 on 2018-03-19 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['track', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['track'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=posts.models.Profile.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_id', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['from_user'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('source', models.FileField(upload_to=posts.models.Track.user_directory_path)),
                ('desc', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=posts.models.Track.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(to='posts.Genre')),
                ('tag', models.ManyToManyField(to='posts.Tag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='posts_tag_name_f0f1cb_idx'),
        ),
        migrations.AddField(
            model_name='sub',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sub',
            name='to_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Track'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['name'], name='posts_genre_name_60e755_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Track'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['title'], name='posts_track_title_36d0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['created_by'], name='posts_track_created_74568c_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['-created_at'], name='posts_track_created_55b57f_idx'),
        ),
        migrations.AddIndex(
            model_name='sub',
            index=models.Index(fields=['from_user', 'to_type'], name='posts_sub_from_us_ab2a50_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['track'], name='posts_like_track_i_8257d0_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['created_by', '-created_at'], name='posts_like_created_58acca_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['track', '-created_at'], name='posts_comme_track_i_c6a187_idx'),
        ),
    ]
