# Generated by Django 2.0.3 on 2018-03-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180321_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_<function get_directory_path_by_id at 0x7f84a048c7b8>/photo/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='source',
            field=models.FileField(upload_to='user_<function get_directory_path_by_id at 0x7f84a048c7b8>/audio/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_<function get_directory_path_by_id at 0x7f84a048c7b8>/photo/'),
        ),
    ]
